### ISSUE TITLE
Allow passing extra keyword arguments to 'find' method

### ISSUE THREAD

**Issue by ymost** [vmalloc/mongomock#160]
In pymongo, you can pass extra keyword arguments to the 'find' method (the method definition ends with "**kwargs"). There extra arguments get sent to the MongoDB server.
Currently trying this with mongomock fails.
An example of such an argument is 'batchSize', but I'm sure there's more.

**Comment by mdomke** [comment]
At least the pymongo 3.x implementation does not allow arbitrary kwargs for the find method, since they are directly handed off as parameters to the `Cursor` class, which has a well defined set of keyword arguments. The currently allowed parameters can be found here:

http://api.mongodb.org/python/current/api/pymongo/collection.html#pymongo.collection.Collection.find

The method signature of the `mongomock.collection.find()` does also allow those parameters, even though not all of them are actually implemented. You can pass `batch_size` to `find()` but actually doesn't do anything.

**Comment by ymost** [comment]
True.
So we should ask ourselves if we aim to support mocking of pymongo 2.x or not.

**Comment by baruchoxman** [comment]
Moving the production code from pymongo 2.x to 3.x is a major change.
It seems very important that mongomock would continue supporting pymongo
2.x in the near future.

**Comment by mdomke** [comment]
I will open a support branch for pymongo 2.x where bugfixes and enhancements can be backported.
